## What is Numpy 

#### Numpy is scientific computing library for python 
#### It is used for mathematical calculations such as linear algebra, Fourier transform and random number capabilities.
#### It support large number of data in the form of multi dimensional array and matrix.

###  import numpy module 

In [1]:
import numpy as np

### 1d array

In [2]:
arr_1d = np.array([1,2,3,4])
print(arr_1d)

[1 2 3 4]


In [3]:
type(arr_1d)

numpy.ndarray

In [4]:
arr_1d.ndim

1

In [5]:
arr_1d.size

4

In [6]:
arr_1d.shape

(4,)

In [7]:
arr_1d.dtype

dtype('int32')

### 2d array

In [8]:
arr_2d = np.array([[1,2,3,4],
                  [5,6,7,8]])

In [9]:
print(arr_2d)

[[1 2 3 4]
 [5 6 7 8]]


In [10]:
arr_2d.ndim

2

In [11]:
arr_2d.size

8

In [12]:
arr_2d.shape #(raw, column)

(2, 4)

In [13]:
arr_2d.dtype

dtype('int32')

### 3d array

In [14]:
arr_3d = np.array([[[1,1,1],[1,1,1],[1,1,1]]])

In [15]:
arr_3d

array([[[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]])

In [16]:
type(arr_3d)

numpy.ndarray

In [17]:
arr_3d.dtype

dtype('int32')

In [18]:
arr_3d.ndim

3

### ones matrix

In [19]:
arr = np.ones((5))

In [20]:
print(arr)

[1. 1. 1. 1. 1.]


In [21]:
arr = np.ones((3,4))

In [22]:
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [23]:
arr = np.ones((3,4), dtype = int)

In [24]:
print(arr)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


### zeros matrix

In [25]:
arr_ze = np.zeros((3,4))

In [26]:
arr_ze

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [27]:
arr_ze = np.zeros((3,4), dtype = bool)

In [28]:
arr_ze

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [29]:
arr_ze = np.zeros((3,4), dtype = str)

In [30]:
arr_ze

array([['', '', '', ''],
       ['', '', '', ''],
       ['', '', '', '']], dtype='<U1')

In [31]:
em_str = ''
print(bool(em_str))

False


###  empty matrix

In [32]:
arr = np.empty((3,3))


In [33]:
arr

array([[0.000e+000, 0.000e+000, 0.000e+000],
       [0.000e+000, 0.000e+000, 5.356e-321],
       [0.000e+000, 0.000e+000, 0.000e+000]])

# Numpy Functions

### arange

In [34]:
arr = np.arange(1,13)

In [35]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

###  linspace

In [36]:
arr = np.linspace(1,5,4)

In [37]:
arr

array([1.        , 2.33333333, 3.66666667, 5.        ])

### reshape

In [38]:
arr = arr.reshape(2,2)

In [39]:
print(arr)

[[1.         2.33333333]
 [3.66666667 5.        ]]


In [40]:
arr = np.arange(1,13)
arr = arr.reshape(2,3,2)

In [41]:
arr

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [42]:
np.arange(1,13).reshape(2,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

### Ravel

In [43]:
arr.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

### flatten

In [44]:
arr = np.arange(1,13).reshape(2,6)
arr.flatten('F')

array([ 1,  7,  2,  8,  3,  9,  4, 10,  5, 11,  6, 12])

### Transpose

In [45]:
arr.transpose()

array([[ 1,  7],
       [ 2,  8],
       [ 3,  9],
       [ 4, 10],
       [ 5, 11],
       [ 6, 12]])

In [46]:
arr.T

array([[ 1,  7],
       [ 2,  8],
       [ 3,  9],
       [ 4, 10],
       [ 5, 11],
       [ 6, 12]])

### Mathematical Operation using Numpy

In [47]:
arr1 = np.arange(1,10).reshape(3,3)
arr2 = np.arange(10,19).reshape(3,3)

In [48]:
print(arr1)
print(arr2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[10 11 12]
 [13 14 15]
 [16 17 18]]


### addition

In [49]:
arr1 + arr2

array([[11, 13, 15],
       [17, 19, 21],
       [23, 25, 27]])

In [50]:
np.add(arr1, arr2)

array([[11, 13, 15],
       [17, 19, 21],
       [23, 25, 27]])

### subtraction

In [51]:
arr1 - arr2

array([[-9, -9, -9],
       [-9, -9, -9],
       [-9, -9, -9]])

In [52]:
np.subtract(arr1, arr2)

array([[-9, -9, -9],
       [-9, -9, -9],
       [-9, -9, -9]])

### elementary multiplication

In [53]:
arr1 * arr2

array([[ 10,  22,  36],
       [ 52,  70,  90],
       [112, 136, 162]])

In [54]:
np.multiply(arr1, arr2)

array([[ 10,  22,  36],
       [ 52,  70,  90],
       [112, 136, 162]])

###  matrix multiplication

In [55]:
arr1 @ arr2

array([[ 84,  90,  96],
       [201, 216, 231],
       [318, 342, 366]])

In [56]:
arr1.dot(arr2)

array([[ 84,  90,  96],
       [201, 216, 231],
       [318, 342, 366]])

### division

In [57]:
arr1 / arr2

array([[0.1       , 0.18181818, 0.25      ],
       [0.30769231, 0.35714286, 0.4       ],
       [0.4375    , 0.47058824, 0.5       ]])

In [58]:
np.divide(arr1, arr2)

array([[0.1       , 0.18181818, 0.25      ],
       [0.30769231, 0.35714286, 0.4       ],
       [0.4375    , 0.47058824, 0.5       ]])

### max

In [59]:
arr1.max()

9

In [60]:
arr1.max(axis = 0) # 0 for column

array([7, 8, 9])

In [61]:
arr1.max(axis = 1) # 1 for row

array([3, 6, 9])

###  max index

In [62]:
arr1.argmax()

8

###  min

In [63]:
arr1.min()

1

In [64]:
arr1.min(axis = 0)

array([1, 2, 3])

In [65]:
arr1.min(axis = 1)

array([1, 4, 7])

In [66]:
arr1.argmin() # argmin for position

0

### sum

In [67]:
arr1.sum()

45

In [68]:
np.sum(arr1)

45

In [69]:
np.sum(arr1, axis = 0) # sum column wise

array([12, 15, 18])

In [70]:
np.sum(arr1, axis = 1) # sum row wise

array([ 6, 15, 24])

###  mean 

In [71]:
np.mean(arr1) # find average 

5.0

### sqrt

In [72]:
np.sqrt(arr1) # find square root

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

### std

In [73]:
np.std(arr1) # find standard deviation

2.581988897471611

### exp

In [74]:
np.exp(arr1) # find exponent

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02],
       [1.09663316e+03, 2.98095799e+03, 8.10308393e+03]])

### log

In [75]:
np.log(arr1)

array([[0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947],
       [1.94591015, 2.07944154, 2.19722458]])

In [76]:
np.log10(arr1)

array([[0.        , 0.30103   , 0.47712125],
       [0.60205999, 0.69897   , 0.77815125],
       [0.84509804, 0.90308999, 0.95424251]])

## Numpy array slicing

In [77]:
arr = np.arange(1,101).reshape(10,10)

In [78]:
print(arr)

[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]


In [79]:
arr[0,0] # [row , column]

1

In [80]:
arr[0,0].ndim

0

In [81]:
arr[0, :]  # 1st row

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [82]:
arr[0].ndim

1

In [83]:
arr[:,0]  # 1st column

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [84]:
arr[:,0:1] # slice 2d array

array([[ 1],
       [11],
       [21],
       [31],
       [41],
       [51],
       [61],
       [71],
       [81],
       [91]])

In [85]:
arr[:,0:1].ndim

2

In [86]:
arr[2:4,2:4]

array([[23, 24],
       [33, 34]])

In [87]:
arr[:, 1:3]

array([[ 2,  3],
       [12, 13],
       [22, 23],
       [32, 33],
       [42, 43],
       [52, 53],
       [62, 63],
       [72, 73],
       [82, 83],
       [92, 93]])

In [88]:
arr[:]

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [89]:
arr[::]

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [90]:
arr[:,:]

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

### itemsize

In [91]:
arr.itemsize # 4 byte space

4

### dtype

In [92]:
arr.dtype

dtype('int32')

### Numpy array concatenate and split

In [93]:
arr1 = np.arange(1,17).reshape(4,4)
arr2 = np.arange(17,33).reshape(4,4)

In [94]:
print(arr1)
print(arr2)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[17 18 19 20]
 [21 22 23 24]
 [25 26 27 28]
 [29 30 31 32]]


In [95]:
np.concatenate((arr1, arr2)) # column wise concatenate

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32]])

In [96]:
np.concatenate((arr1, arr2), axis = 1) # row wise concatenate

array([[ 1,  2,  3,  4, 17, 18, 19, 20],
       [ 5,  6,  7,  8, 21, 22, 23, 24],
       [ 9, 10, 11, 12, 25, 26, 27, 28],
       [13, 14, 15, 16, 29, 30, 31, 32]])

In [97]:
np.vstack((arr1,arr2)) # vertical concatenate

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32]])

In [98]:
np.hstack((arr1, arr2))  # horizontal concatenate

array([[ 1,  2,  3,  4, 17, 18, 19, 20],
       [ 5,  6,  7,  8, 21, 22, 23, 24],
       [ 9, 10, 11, 12, 25, 26, 27, 28],
       [13, 14, 15, 16, 29, 30, 31, 32]])

In [99]:
np.hstack((arr1, arr2, arr1))

array([[ 1,  2,  3,  4, 17, 18, 19, 20,  1,  2,  3,  4],
       [ 5,  6,  7,  8, 21, 22, 23, 24,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 25, 26, 27, 28,  9, 10, 11, 12],
       [13, 14, 15, 16, 29, 30, 31, 32, 13, 14, 15, 16]])

### split

In [100]:
np.split(arr1, 2)

[array([[1, 2, 3, 4],
        [5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12],
        [13, 14, 15, 16]])]

In [101]:
np.split(arr1, 2, axis = 1)

[array([[ 1,  2],
        [ 5,  6],
        [ 9, 10],
        [13, 14]]),
 array([[ 3,  4],
        [ 7,  8],
        [11, 12],
        [15, 16]])]

In [102]:
arr = np.split(arr1, 2) # split and store in list type 
type(arr)

list

In [103]:
type(arr[0])

numpy.ndarray

In [104]:
arr = np.array([4,7,5,3])

In [105]:
np.split(arr, [1,3])

[array([4]), array([7, 5]), array([3])]

### Trignometry functions

In [106]:
np.sin(180)

-0.8011526357338304

In [107]:
np.sin(90*np.pi/180) # value in degree or radian

1.0

In [108]:
np.cos(180)

-0.5984600690578582

In [109]:
np.cos(90)

-0.4480736161291701

In [110]:
np.tan(180)

1.3386902103511544

In [111]:
np.tan(90)

-1.995200412208242

In [112]:
x_sin = np.arange(0, 3*np.pi, 0.1)
print(x_sin)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1.  1.1 1.2 1.3 1.4 1.5 1.6 1.7
 1.8 1.9 2.  2.1 2.2 2.3 2.4 2.5 2.6 2.7 2.8 2.9 3.  3.1 3.2 3.3 3.4 3.5
 3.6 3.7 3.8 3.9 4.  4.1 4.2 4.3 4.4 4.5 4.6 4.7 4.8 4.9 5.  5.1 5.2 5.3
 5.4 5.5 5.6 5.7 5.8 5.9 6.  6.1 6.2 6.3 6.4 6.5 6.6 6.7 6.8 6.9 7.  7.1
 7.2 7.3 7.4 7.5 7.6 7.7 7.8 7.9 8.  8.1 8.2 8.3 8.4 8.5 8.6 8.7 8.8 8.9
 9.  9.1 9.2 9.3 9.4]


In [113]:
y_sin = np.sin(x_sin)

In [114]:
print(y_sin)

[ 0.          0.09983342  0.19866933  0.29552021  0.38941834  0.47942554
  0.56464247  0.64421769  0.71735609  0.78332691  0.84147098  0.89120736
  0.93203909  0.96355819  0.98544973  0.99749499  0.9995736   0.99166481
  0.97384763  0.94630009  0.90929743  0.86320937  0.8084964   0.74570521
  0.67546318  0.59847214  0.51550137  0.42737988  0.33498815  0.23924933
  0.14112001  0.04158066 -0.05837414 -0.15774569 -0.2555411  -0.35078323
 -0.44252044 -0.52983614 -0.61185789 -0.68776616 -0.7568025  -0.81827711
 -0.87157577 -0.91616594 -0.95160207 -0.97753012 -0.993691   -0.99992326
 -0.99616461 -0.98245261 -0.95892427 -0.92581468 -0.88345466 -0.83226744
 -0.77276449 -0.70554033 -0.63126664 -0.55068554 -0.46460218 -0.37387666
 -0.2794155  -0.1821625  -0.0830894   0.0168139   0.1165492   0.21511999
  0.31154136  0.40484992  0.49411335  0.57843976  0.6569866   0.72896904
  0.79366786  0.85043662  0.8987081   0.93799998  0.96791967  0.98816823
  0.99854335  0.99894134  0.98935825  0.96988981  0

In [115]:
y_cos = np.cos(x_sin)

In [116]:
print(y_cos)

[ 1.          0.99500417  0.98006658  0.95533649  0.92106099  0.87758256
  0.82533561  0.76484219  0.69670671  0.62160997  0.54030231  0.45359612
  0.36235775  0.26749883  0.16996714  0.0707372  -0.02919952 -0.12884449
 -0.22720209 -0.32328957 -0.41614684 -0.5048461  -0.58850112 -0.66627602
 -0.73739372 -0.80114362 -0.85688875 -0.90407214 -0.94222234 -0.97095817
 -0.9899925  -0.99913515 -0.99829478 -0.98747977 -0.96679819 -0.93645669
 -0.89675842 -0.84810003 -0.79096771 -0.7259323  -0.65364362 -0.57482395
 -0.49026082 -0.40079917 -0.30733287 -0.2107958  -0.11215253 -0.01238866
  0.08749898  0.18651237  0.28366219  0.37797774  0.46851667  0.55437434
  0.63469288  0.70866977  0.77556588  0.83471278  0.88551952  0.92747843
  0.96017029  0.98326844  0.9965421   0.99985864  0.99318492  0.97658763
  0.95023259  0.91438315  0.86939749  0.8157251   0.75390225  0.68454667
  0.60835131  0.52607752  0.43854733  0.34663532  0.25125984  0.15337386
  0.05395542 -0.04600213 -0.14550003 -0.24354415 -0

###  Random sampling with numpy 

### random

In [117]:
np.random.random(1) # gives value btw 0-1

array([0.72641124])

In [118]:
np.random.random((3,3))

array([[0.37944706, 0.52900084, 0.29732852],
       [0.20771669, 0.20339015, 0.01991284],
       [0.90344544, 0.08552926, 0.76068543]])

###  randint


In [119]:
np.random.randint(1,4) 

3

In [120]:
np.random.randint(1,4,(4,4)) # pass tuple for size

array([[1, 3, 1, 3],
       [3, 3, 2, 2],
       [1, 3, 2, 1],
       [2, 3, 1, 1]])

In [121]:
np.random.randint(1,4,(2,4,4))

array([[[1, 1, 1, 2],
        [2, 3, 2, 3],
        [1, 1, 2, 2],
        [1, 2, 1, 3]],

       [[2, 3, 1, 1],
        [2, 2, 3, 3],
        [2, 1, 1, 3],
        [2, 2, 2, 1]]])

### seed 

In [122]:
np.random.seed(10) # 2**32 -1 muplite type
np.random.randint(1,4,(2,4,4))

array([[[2, 2, 1, 1],
        [2, 1, 2, 2],
        [1, 2, 2, 3],
        [1, 2, 1, 3]],

       [[1, 3, 1, 1],
        [1, 3, 1, 3],
        [3, 2, 1, 1],
        [3, 2, 3, 2]]])

In [123]:
np.random.seed(10)
np.random.randint(1,4,(2,4,4))

array([[[2, 2, 1, 1],
        [2, 1, 2, 2],
        [1, 2, 2, 3],
        [1, 2, 1, 3]],

       [[1, 3, 1, 1],
        [1, 3, 1, 3],
        [3, 2, 1, 1],
        [3, 2, 3, 2]]])

###  rand

In [124]:
np.random.rand(3) # value btw 0-1

array([0.13145815, 0.41366737, 0.77872881])

In [125]:
np.random.rand(3,3)

array([[0.58390137, 0.18263144, 0.82608225],
       [0.10540183, 0.28357668, 0.06556327],
       [0.05644419, 0.76545582, 0.01178803]])

### randn

In [126]:
np.random.randn(3,3) # value btw -1 to 1

array([[-1.58494101,  1.05535316, -1.92657911],
       [ 0.69858388, -0.74620143, -0.15662666],
       [-0.19363594,  1.13912535,  0.36221796]])

### choice

In [127]:
x = [1,2,3,4]   # choice from given list
np.random.choice(x)

1

### permutation

In [128]:
np.random.permutation(x)

array([3, 2, 4, 1])

### shuffle

In [129]:
np.random.shuffle(x)

In [130]:
x

[2, 3, 4, 1]

###  string Operations

In [131]:
ch_name  = "Indian AI Production"
str1 = "Learning Python Numpy"

In [132]:
np.char.add(ch_name, str1)

array('Indian AI ProductionLearning Python Numpy', dtype='<U41')

In [133]:
np.char.lower(ch_name)

array('indian ai production', dtype='<U20')

In [134]:
np.char.upper(str1)

array('LEARNING PYTHON NUMPY', dtype='<U21')

In [135]:
np.char.title(str1)

array('Learning Python Numpy', dtype='<U21')

In [136]:
np.char.center(ch_name, 60)

array('                    Indian AI Production                    ',
      dtype='<U60')

In [137]:
np.char.center(ch_name, 60, fillchar = '*')

array('********************Indian AI Production********************',
      dtype='<U60')

In [138]:
np.char.split(str1)

array(list(['Learning', 'Python', 'Numpy']), dtype=object)

In [139]:
np.char.splitlines("hello\nIndian")

array(list(['hello', 'Indian']), dtype=object)

In [140]:
str4  = "dmy"
str5 = "dmy"

In [141]:
np.char.join([":","/"],[str4,str5])

array(['d:m:y', 'd/m/y'], dtype='<U5')

In [142]:
np.char.join([":"],[str4])

array(['d:m:y'], dtype='<U5')

In [143]:
np.char.replace(ch_name, "AI" ,"Artificial Intelligent")

array('Indian Artificial Intelligent Production', dtype='<U40')

### string comparsion

In [144]:
np.char.equal(str4,str5)

array(True)

In [145]:
np.char.equal(ch_name,str5)

array(False)

In [146]:
np.char.count(ch_name,"a")

array(1)

In [147]:
np.char.find(ch_name, 'P')

array(10)